services:
  log-stash-lite:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    environment:
      - LISTEN_ADDR=:8080
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=change_me
      - ELASTIC_URL=http://localhost:9200


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
