definitions:
  dto.AddLogRequest:
    properties:
      log:
        additionalProperties: true
        type: object
      parse_type:
        enum:
        - default
        - zap
        - logrus
        - pino
        type: string
    required:
    - log
    - parse_type
    type: object
  dto.AddLogResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  dto.AddLogsRequest:
    properties:
      logs:
        items:
          additionalProperties: true
          type: object
        minItems: 1
        type: array
      parse_type:
        enum:
        - default
        - zap
        - logrus
        - pino
        type: string
    required:
    - logs
    - parse_type
    type: object
  dto.AddLogsResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.GetLogsCountResponse:
    properties:
      count:
        type: integer
    type: object
  dto.GetLogsResponse:
    properties:
      count:
        type: integer
      logs:
        items:
          additionalProperties: true
          type: object
        type: array
    type: object
  dto.HealthResponse:
    properties:
      elastic_status:
        type: string
      error:
        type: string
      status:
        type: string
      system_status:
        properties:
          cpu:
            properties:
              temperature:
                type: number
              usage_percent:
                type: number
            type: object
          ram:
            properties:
              total_mb:
                type: integer
              used_mb:
                type: integer
            type: object
          rom:
            properties:
              total_mb:
                type: integer
              used_mb:
                type: integer
            type: object
        type: object
    type: object
info:
  contact: {}
paths:
  /add_log:
    post:
      consumes:
      - application/json
      description: Adds a single log entry to storage
      parameters:
      - description: Log entry
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AddLogRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AddLogResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Add a log entry
      tags:
      - logs
  /add_logs:
    post:
      consumes:
      - application/json
      description: Adds multiple log entries to storage
      parameters:
      - description: Log entries
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AddLogsRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AddLogsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Add multiple log entries
      tags:
      - logs
  /get_logs:
    get:
      consumes:
      - application/json
      description: Returns logs with filters and limit
      parameters:
      - description: Log level
        in: query
        name: level
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetLogsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get logs
      tags:
      - logs
  /get_logs_count:
    get:
      consumes:
      - application/json
      description: Returns only count of logs by filters
      parameters:
      - description: Log level
        in: query
        name: level
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetLogsCountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get logs count
      tags:
      - logs
  /health:
    get:
      description: Returns health status of the service and system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HealthResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/dto.HealthResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
